### ISSUE TITLE
Tree + Modular Fungi Lights Off

### ISSUE THREAD

**Issue by ContemporaryInsanity** [jeremywen/JW-Modules#69] opened 2020-11-08 12:52 UTC
Enabling Lights Off hides Tree inputs & controls and Tree draws out of panel.

![image](https://user-images.githubusercontent.com/12547379/98465496-4aaa1f80-21c1-11eb-8fcf-c0ab0ed41345.png)

**Comment by jeremywen** [comment] 2020-11-08 14:32
Noticed while testing.  Also happens for ThingThing.  I believe this happens for any light widget by design.  Maybe @stoermelder knows for sure?

**Comment by stoermelder** [comment] 2020-11-08 15:13
Yes, in `draw` of `ModuleWidget` everything is scissored to the module bounds. LightsOff does not do this and it is no problem as long a `LightWidget` does not outside of its own bounds.
It should be fixed by adding `nvgScissor(args.vg, RECT_ARGS(box))` as first line and `nvgResetScissor(args.vg)` as last line in `draw` of your `LightWidget`.

**Comment by jeremywen** [comment] 2020-11-08 15:24
Fixed.  Thank you @stoermelder !!!

**Closed** 2020-11-08 20:14 UTC
